### ISSUE TITLE
Chat window not opening on bubble click

### ISSUE THREAD

**Issue by Miteshb96** [livechat/react-native-livechat#18]
Hi,

I am not able to open chat window properly on bubble click on icon some part of window is not visible and not able to enter any input in the windows
![livechat_problem](https://user-images.githubusercontent.com/40490241/50284338-c5a7a700-047e-11e9-8c00-864034a41b15.png)

**Comment by venits** [comment]
Hi,
It is happening because `<LiveChat  />` must be called in the root of application. 
It uses `absolute` positioning.

What you can do to fix it right now is to remove all `align-items: center` and `justify-content: center` from your styles.

Doing so absolute view will be moved to top-left side of the screen.
